---
- hosts: all
  become: yes
  tasks:
  - name: i want to install apache2
    apt:
      name: apache2
      status : present

  - name: i want to start apache2 services
    service:
      name: apache2
      status : started
     
