---
- hosts: mywebservers
  become: yes
  tasks:
  - name: i want to install apache2
    apt:
      name: "{{mywebpackonubuntu}}"
      state : present

  - name: i want to start apache2 services
    service:
      name: "{{mywebpackonubuntu}}"
      state : started
     
